spring:
  datasource:
    url: jdbc:mysql://localhost:3307/anniversary_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

app:
  jwt:
    secret: test-secret-key-for-development-must-be-at-least-256-bits
    expiration-ms: 86400000
  upload:
    dir: ${java.io.tmpdir}/anniversary_uploads_test
  cors:
    allowed-origins: http://localhost:5173

logging:
  level:
    root: INFO
    com.couple.anniversary: DEBUG
